### ISSUE TITLE
Incompatible whith fresh animation

### ISSUE THREAD

**Issue by Mozork01** [Khajiitos/ChestedCompanions#1]
Chest texture incompatible with fresh animation

**Comment by Mozork01** [comment]
![2024-03-10_18 52 30](https://github.com/Khajiitos/ChestedCompanions/assets/148884018/06a37d31-be60-4cf2-b8a2-961eec8b2620)

**Comment by Mozork01** [comment]
Maybe add an option to hide chests

**Comment by Khajiitos** [comment]
That resource pack works with another mod to override the cat's model, and because of this the mod doesn't get the right position for the cat's body. There is nothing that I can do about this, but I can add the ability to hide the chest in the config in the future update.

**Comment by Mozork01** [comment]
I understand it's difficult. This is why I suggested the option to hide. Thanks for doing it! Maybe show that the animal is carrying a chest in another way ?

**Comment by Mozork01** [comment]
I have an idea.  When you put a chest on a wolf or a cat, it adds a suffix to the entity's first name.  Example "Wolf with a chest" the suffix could be customizable in modmenu.  You should also have the option to show or hide the suffix.

**Comment by Khajiitos** [comment]
I decided I will add an option to display a chest icon above the pet, its position will be adjusted to be more in the center and not render over the nametag, and it will be displayed only if the pet is on the crosshair.

![image](https://github.com/Khajiitos/ChestedCompanions/assets/58109276/4d69298d-30b9-4e4a-8ca7-03bf370d61f2)

**Comment by Mozork01** [comment]
Thanks !

**Comment by Mozork01** [comment]
Are you going to add it to horses?

**Comment by Khajiitos** [comment]
> Are you going to add it to horses?

Nope, this mod is only supposed to work for cats and dogs, and the chest icon is only a substitute in case of model incompatibilities caused by other mods.

I've released an update that adds config options to hide the chest (1.2.0), however I have to postpone adding the chest icon for a future update, as I've had some trouble rendering it the way I wanted to, that is, facing the player like name tags.
