### ISSUE TITLE
Crash

### ISSUE THREAD

**Issue by Mozork01** [Khajiitos/ChestedCompanions#2]
Fabric 1.20.1

Crash sometimes when I open the chest by sneak + right click

[crash-2024-03-10_19.53.13-server.txt](https://github.com/Khajiitos/ChestedCompanions/files/14551422/crash-2024-03-10_19.53.13-server.txt)

**Comment by Khajiitos** [comment]
Are you using the 1.20.4 version of the [Not Interested](https://www.curseforge.com/minecraft/mc-mods/not-interested) mod on 1.20.1? I can't guarantee that that mod is the reason of the crash, but it would be nice if you could check if the crash persists when you remove that mod.

**Comment by Mozork01** [comment]
You are right. I noticed it. I didn't have time to close the ticket. 😰
I sometimes manage to modify mods to make them compatible in the correct versions. But I forgot that I installed this mod at the same time as yours
