### ISSUE TITLE
Allow Chests? [Fabric 1.20.1]

### ISSUE THREAD

**Issue by Dumpling00** [Khajiitos/ChestedCompanions#3]
Greetings! Big fan of the concept! I've noticed some incompatibilities with FreshAnimations, namely on the cat model, where the chests are pinned to the very back of the model rather than sitting on the sides. It works absolutely fine on Dogs!

I know there's an option to hide them, but is there any chance we could just get an option to not allow chests on either cats or dogs at all? I know it's very situational, but to me I think it makes more sense in this case, where I'd like to allow my dogs to carry chests (they're big enough for it!) but not necessarily have any on cats.

I know the simple solution to this is just "Don't put chests on cats then" but I'm hosting a game with other friends and, I know some of them would take the opportunity to have extra storage either way and just make the chests invisible, which is a bit cheaty in my eyes.

Could we then please have an option to simply not allow either cats or dogs to have chests? If fixing the compatibility is too tricky, this might do.

Thank you for your time and consideration.

**Comment by Khajiitos** [comment]
Good idea, I will definitely add that option in the next update!

**Comment by Dumpling00** [comment]
Awesome, thank you! Also any chance you could upload the mod to modrinth? I've found it on curseforge by pure chance, while I mostly check modrinth on a daily basis! 
If it's not too much trouble of course, I bet it would make it accessible to a lot more people - it's such a neat concept, more people deserve to know, haha!

**Comment by Khajiitos** [comment]
I didn't upload this mod on Modrinth because it's a bit of a hassle to upload all mod versions twice, however I am working on automating parts of the uploading process, and I will happily upload the mod to Modrinth then.

**Comment by Khajiitos** [comment]
Added in 1.2.2
